### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by MohammedAdain** [codebynumbers/ftpretty#44]
I am not able to 
```
>>> from ftpretty import ftpretty
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adain/projects/transfers/exp/ftpretty.py", line 2, in <module>
    from ftpretty import ftpretty
ImportError: cannot import name 'ftpretty' from 'ftpretty' (/home/adain/projects/transfers/exp/ftpretty.py)
```

FYI,
```
pip freeze
ftpretty==0.4.0
python-dateutil==2.8.2
six==1.16.0
```

```
python --version
Python 3.7.16
```

**Comment by MohammedAdain** [comment]
Please disregard this, the issue was I had created a local file named ftpretty /home/adain/projects/transfers/exp/ftpretty.py and python was trying to install it from the local file which didnot have a module name ftpretty.
